# Generated by Django 3.1.2 on 2021-01-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210125_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='token'),
        ),
    ]
