# Generated by Django 3.1.2 on 2021-01-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('O', 'others'), ('P', 'prefer not to say')], max_length=10, null=True, verbose_name='gender'),
        ),
    ]
