# Generated by Django 3.1.2 on 2021-01-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210127_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifyrecord',
            old_name='send_time',
            new_name='sendTime',
        ),
        migrations.RenameField(
            model_name='emailverifyrecord',
            old_name='send_type',
            new_name='sendType',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='createDate',
            new_name='createTime',
        ),
    ]
