# Generated by Django 3.1.2 on 2021-01-27 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210127_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=20, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='sendTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 19, 32, 57, 406860)),
        ),
    ]
