# Generated by Django 3.1.2 on 2021-01-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210127_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='sendTime',
            field=models.DateTimeField(),
        ),
    ]
