# Generated by Django 3.1.2 on 2021-05-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210520_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='sendTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
