# Generated by Django 3.1.2 on 2021-05-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210520_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='code'),
        ),
    ]
