# Generated by Django 3.1.2 on 2021-01-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='recipecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
